name: Build Windows EXE (PyInstaller onedir)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Verify assets (icon optional)
        shell: bash
        run: |
          if [ -f "assets/app.ico" ]; then
            echo "Found assets/app.ico"
          else
            echo "WARNING: assets/app.ico not found. EXE will use default icon."
          fi

      - name: Build (PyInstaller onedir windowed)
        shell: bash
        run: >
          python -m PyInstaller app.py
          --noconfirm
          --clean
          --onedir
          --windowed
          --name WhiteBoard
          --icon assets/app.ico
          --collect-submodules PySide6
          --hidden-import PySide6.QtMultimedia

      - name: Copy repo assets into dist (optional at runtime)
        shell: bash
        run: |
          if [ -d "assets" ]; then
            mkdir -p dist/WhiteBoard/assets
            cp -r assets/* dist/WhiteBoard/assets/ || true
          fi

      - name: Upload artifact (folder)
        uses: actions/upload-artifact@v4
        with:
          name: WhiteBoard_onedir_Windows
          path: dist/WhiteBoard/**
          if-no-files-found: error



