name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
          # PyInstaller y runtime Qt
          pip install pyinstaller PySide6 qdarkstyle

      - name: Verify assets exist
        shell: pwsh
        run: |
          if (!(Test-Path "assets/app.ico")) { throw "Falta assets/app.ico" }
          Write-Host "Assets:"
          Get-ChildItem assets

      - name: Build EXE (onedir, windowed, con assets)
        shell: pwsh
        run: >
          python -m PyInstaller app.py
          --noconfirm --clean --onedir --windowed
          --name WhiteBoard
          --icon assets/app.ico
          --collect-submodules PySide6
          --hidden-import PySide6.QtMultimedia
          --add-data "assets/app.ico;assets"
          --add-data "assets/app.png;assets"

      - name: List dist
        shell: pwsh
        run: |
          Get-ChildItem -Recurse dist\WhiteBoard

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WhiteBoard-windows
          path: dist/WhiteBoard/




